# =========================
# SERVER 1
# =========================
server {
    listen 8080;
    server_name localhost a.com ;

    root ./www/site1;
    index index.html;

    client_max_body_size 100M;

    error_page 404 /errors/404.html;

    # Route simple
    location / {
        allow_methods GET POST;
    }

    # Route upload
    location /upload {
        root ./www/upload;
        allow_methods POST;
    }

    # Route avec DELETE autorisé
    location /delete {
        allow_methods GET DELETE;
    }

    # CGI exemple
    location /cgi-bin {
        allow_methods GET POST;
        root ./www;
        cgi_ext .py;
        cgi_path /usr/bin/python3;
    }
}

# =========================
# SERVER 2
# =========================
server {
    listen 9090;
    server_name example.com b.com example.com;

    root ./www/site2;
    index home.html;

    client_max_body_size 10;

    error_page 404 /404.html;

    location / {
        allow_methods GET;
    }

    location /images {
        root ./www/assets;
        allow_methods GET;
    }
}